tauri::generate_handler![
    commands::core::health_check, commands::core::check_model_status, commands::core::chat_completion, commands::story::list_stories, commands::story::create_story, commands::story::update_story, commands::story::delete_story,
    commands::character::get_story_characters, commands::character::create_character, commands::character::update_character, commands::character::delete_character,
    commands::chapter::get_story_chapters, commands::chapter::get_story_chapters_paged, commands::chapter::get_chapter, commands::chapter::create_chapter, commands::chapter::update_chapter, commands::chapter::delete_chapter,
    commands::skill::get_skills, commands::skill::get_skill,
    commands::skill::import_skill, commands::skill::enable_skill, commands::skill::disable_skill, commands::skill::uninstall_skill, commands::skill::execute_skill, commands::skill::update_skill, commands::skill::format_text,
    commands::mcp::connect_mcp_server, commands::mcp::call_mcp_tool, commands::mcp::disconnect_mcp_server, commands::mcp::get_mcp_connections, commands::mcp::list_mcp_tools, commands::mcp::execute_mcp_tool, commands::mcp::register_mcp_tool, commands::mcp::unregister_mcp_tool,
    commands::vector::search_similar, commands::vector::text_search_vectors, commands::vector::hybrid_search_vectors,
    commands::export::export_story, commands::export::list_export_templates,
    commands::ai_op::list_ai_operations, commands::ai_op::rollback_ai_operation,
    // Window management commands
    window::show_frontstage,
    window::hide_frontstage,
    window::toggle_frontstage,
    window::get_window_state,
    window::update_frontstage_content,
    // Backstage communication commands
    commands::sync::notify_backstage_content_changed,
    commands::sync::notify_frontstage_content_changed,
    commands::sync::notify_frontstage_data_refresh,
    commands::sync::show_backstage,
    commands::sync::cancel_genesis_pipeline,
    // Settings commands
    config::get_settings,
    config::save_settings,
    config::export_settings,
    config::import_settings,
    config::get_models,
    config::get_model_api_key,
    config::create_model,
    config::update_model,
    config::delete_model,
    config::set_active_model,
    config::get_agent_mappings,
    config::update_agent_mapping,
    config::test_model_connection,
    config::fetch_models,
    router::simulate_route,
    router::benchmark_model_for_task,
    router::get_model_health_reports,
    router::submit_route_feedback,
    // v0.17.1: 提示词注册表 IPC
    prompts::commands::list_prompt_entries,
    prompts::commands::save_prompt_override,
    prompts::commands::reset_prompt_override,
    prompts::commands::reset_all_prompt_overrides,
    prompts::commands::resolve_prompt_content,
    model_gateway::commands::get_gateway_status,
    model_gateway::commands::refresh_model_health,
    model_gateway::commands::simulate_gateway_route,
    model_gateway::commands::probe_model_gateway,
    // LLM commands
    llm::commands::llm_generate,
    llm::commands::llm_generate_stream,
    llm::commands::llm_cancel_generation,
    llm::commands::llm_cancel_all_generations,
    // Intent commands
    commands::intent::parse_intent,
    commands::intent::execute_intent,
    commands::intent::record_feedback,
    // Smart orchestrator
    commands::orchestrator::check_preflight,
    commands::orchestrator::smart_execute,
    commands::orchestrator::get_input_hint,
    // Agent commands (仅保留前端有调用的)
    agents::commands::agent_execute_stream,
    agents::commands::agent_cancel_task,
    agents::commands::agent_cancel_all_tasks,
    agents::commands::auto_write,
    agents::commands::auto_revise,
    // Subscription commands
    subscription::commands::get_subscription_status,
    subscription::commands::dev_upgrade_subscription,
    subscription::commands::dev_downgrade_subscription,
    // Updater commands
    updater::check_update,
    updater::install_update,
    updater::get_current_version,
    // Scene & knowledge graph commands
    scene_commands::create_scene,
    scene_commands::get_story_scenes,
    scene_commands::get_story_scenes_paged,
    scene_commands::get_story_word_count,
    scene_commands::get_scene,
    scene_commands::update_scene,
    scene_commands::delete_scene,
    scene_commands::reorder_scenes,
    studio_commands::create_world_building,
    studio_commands::get_world_building,
    studio_commands::update_world_building,
    studio_commands::delete_world_building,
    studio_commands::create_writing_style,
    studio_commands::get_writing_style,
    studio_commands::update_writing_style,
    studio_commands::create_studio_config,
    studio_commands::get_studio_config,
    studio_commands::update_studio_config,
    studio_commands::export_studio,
    studio_commands::import_studio,
    studio_commands::create_entity,
    studio_commands::update_entity,
    studio_commands::get_story_entities,
    studio_commands::create_relation,
    studio_commands::get_entity_relations,
    studio_commands::get_ingest_jobs,
    studio_commands::get_story_graph,
    studio_commands::get_retention_report,
    studio_commands::archive_forgotten_entities,
    studio_commands::restore_archived_entity,
    studio_commands::get_archived_entities,
    // Scene annotations
    scene_commands::create_scene_annotation,
    scene_commands::get_scene_annotations,
    scene_commands::get_story_unresolved_annotations,
    scene_commands::update_scene_annotation,
    scene_commands::resolve_scene_annotation,
    scene_commands::unresolve_scene_annotation,
    scene_commands::delete_scene_annotation,
    // Text inline annotations
    scene_commands::create_text_annotation,
    scene_commands::get_text_annotations_by_chapter,
    scene_commands::get_text_annotations_by_scene,
    scene_commands::update_text_annotation,
    scene_commands::resolve_text_annotation,
    scene_commands::unresolve_text_annotation,
    scene_commands::delete_text_annotation,
    // Commentator agent
    scene_commands::generate_paragraph_commentaries,
    // Memory compressor
    studio_commands::compress_content,
    studio_commands::compress_scene,
    // Knowledge distiller
    studio_commands::distill_story_knowledge,
    studio_commands::get_story_summaries,
    studio_commands::update_story_summary,
    studio_commands::delete_story_summary,
    // Novel creation wizard commands
    creation_commands::generate_world_building_options,
    creation_commands::generate_character_profiles,
    creation_commands::generate_writing_styles,
    creation_commands::generate_first_scene,
    creation_commands::create_story_with_wizard,
    // Scene version commands
    scene_commands::get_scene_versions,
    scene_commands::get_scene_version,
    scene_commands::create_scene_version,
    scene_commands::compare_scene_versions,
    scene_commands::restore_scene_version,
    scene_commands::get_scene_version_stats,
    scene_commands::delete_scene_version,
    scene_commands::get_scene_version_chain,
    scene_commands::get_version_change_tracks,
    // Change tracking (revision mode)
    revision_commands::track_change,
    revision_commands::accept_change,
    revision_commands::reject_change,
    revision_commands::get_pending_changes,
    revision_commands::accept_all_changes,
    revision_commands::reject_all_changes,
    // Comment threads (revision mode)
    revision_commands::create_comment_thread,
    revision_commands::add_comment_message,
    revision_commands::get_comment_threads,
    revision_commands::resolve_comment_thread,
    revision_commands::reopen_comment_thread,
    revision_commands::delete_comment_thread,
    creation_commands::run_creation_workflow,
    creation_commands::list_style_dnas,
    creation_commands::set_story_style_dna,
    creation_commands::analyze_style_sample,
    // Style blend commands
    creation_commands::get_story_style_blend,
    creation_commands::set_story_style_blend,
    creation_commands::update_scene_style_blend,
    creation_commands::check_style_drift,
    // Book deconstruction commands
    book_deconstruction::commands::upload_book,
    book_deconstruction::commands::get_analysis_status,
    book_deconstruction::commands::get_book_analysis,
    book_deconstruction::commands::list_reference_books,
    book_deconstruction::commands::delete_reference_book,
    book_deconstruction::commands::convert_book_to_story,
    book_deconstruction::commands::cancel_book_analysis,
    // Task system commands
    task_system::commands::create_task,
    task_system::commands::update_task,
    task_system::commands::delete_task,
    task_system::commands::list_tasks,
    task_system::commands::trigger_task,
    task_system::commands::cancel_task,
    task_system::commands::get_task_logs,
    task_system::commands::run_ai_generation_task,
    task_system::commands::run_pipeline_task,
    // Foreshadowing tracker commands
    creation_commands::get_story_foreshadowings,
    creation_commands::create_foreshadowing,
    creation_commands::update_foreshadowing_status,
    // Payoff Ledger commands
    creation_commands::get_payoff_ledger,
    creation_commands::detect_overdue_payoffs,
    creation_commands::recommend_payoff_timing,
    creation_commands::update_payoff_ledger_fields,
    // Canonical state commands
    // Structured outline commands
    creation_commands::generate_scene_outline,
    creation_commands::generate_scene_draft,
    // Audit commands
    audit::commands::audit_scene,
    commands::audit::audit_story,
    // Auth commands
    auth::commands::get_auth_config,
    auth::commands::oauth_start,
    auth::commands::oauth_callback,
    auth::commands::get_current_user,
    auth::commands::logout,
    // Genesis Engine commands
    creation_commands::get_story_outline,
    creation_commands::update_story_outline,
    revision_commands::get_character_relationships,
    revision_commands::create_character_relationship,
    revision_commands::update_character_relationship,
    revision_commands::delete_character_relationship,
    // Scene-Character association commands
    studio_commands::get_character_by_name,
    studio_commands::check_projection_health,
    studio_commands::get_writing_analytics,
    // Generic Workflow commands — 仅保留前端查询命令
    commands::workflow::list_workflows,
    commands::workflow::reload_workflows,
    // Logging commands
    // Story System commands
    commands::story_system::create_master_setting,
    commands::story_system::create_chapter_contract,
    commands::story_system::get_contract_tree,
    commands::story_system::get_runtime_contract,
    commands::story_system::init_chapter_commit,
    commands::story_system::get_chapter_commits,
    commands::story_system::list_genesis_runs,
    commands::story_system::get_genesis_run,
    commands::story_system::get_latest_style_snapshot,
    // Memory commands
    commands::memory::build_memory_pack,
    commands::memory::get_memory_items,
    commands::memory::create_memory_item,
    // Reading Power commands
    commands::reading_power::evaluate_reading_power,
    commands::reading_power::get_reading_power_trend,
    commands::reading_power::get_chase_debts,
    commands::reading_power::create_override_contract,
    // Genre Profile commands
    commands::genre::get_genre_profiles,
    commands::genre::get_genre_profile,
    commands::genre::save_genre_profile,
    commands::genre::delete_genre_profile,
    // Strategy selection command
    commands::strategy::select_creation_strategy,
    // Anti-AI Review command
    commands::anti_ai::anti_ai_review,
    commands::anti_ai::evolve_style_from_anti_ai_review,
    commands::anti_ai::log_frontend_feature_usage,
    // Pipeline data commands (frontend depends on these)
    pipeline::commands::get_story_chapter_drafts,
    pipeline::commands::get_latest_pipeline_review,
    llm::commands::get_story_llm_calls,
    llm::commands::get_recent_llm_calls,
    llm::commands::get_llm_call_stats,
    scene_commands::update_character_state,
    scene_commands::trigger_cascade_rewrite,
    // Pipeline orchestrator commands
    pipeline::commands::run_refine,
    pipeline::commands::run_review,
    pipeline::commands::run_finalize,
    pipeline::commands::repair_finalize,
    pipeline::commands::get_post_process_status,
    pipeline::commands::get_pipeline_active_draft,
    pipeline::commands::merge_revision,
    pipeline::commands::get_draft_revision_history,
    pipeline::commands::get_draft_review_history,
    // Auto Contract commands
    commands::pipeline::auto_create_missing_contracts,
    // Cascade Rewriter commands
    creative_engine::cascade_rewriter::commands::get_cascade_rewrite_result,
    creative_engine::cascade_rewriter::commands::apply_cascade_rewrite,
    creative_engine::cascade_rewriter::commands::reject_cascade_rewrite,
    // LitSeg 叙事感知分段命令
    commands::narrative::analyze_narrative_structure,
    commands::narrative::get_narrative_events,
    commands::narrative::get_narrative_threads,
    commands::narrative::get_narrative_chunks,
]